name: .NET

on:
  push:
    branches: ["master"]
    # paths-ignore:
    # - '.github/**'
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Push package
        run: |
          # versioning
          commithash=$(git rev-parse --short HEAD)
          currtime=$(date +%s)
          echo "commit hash is $commithash"
          echo "time is $currtime"
          name=1.2-$currtime-$commithash
          echo "name is $name"

          # Manganese
          cd Manganese
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget add source --username SinoAHpx --password ${{ secrets.PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SinoAHpx/index.json"
          dotnet nuget push Manganese.$name.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "github"
